### ISSUE TITLE
lv페어 리뷰입니다. 

### ISSUE THREAD

**Issue by haechanlee96** [iksadNorth/Lv1-Assignment#2]
1. 예외처리를 보기 쉽게 따로 관리하는게 좋은 것 같습니다. / 어떤 예외처리를 한 것인지 궁금합니다.
2. entity 에 각 변수들을 @column 값으로 처리하지 않고 다른 어노테이션들을 사용했는데, 어떤 이점이 있는지 궁금합니다.
3. 데이터를 받는 객체를 dto로 알고 있는데, 여기서는 model로 처리하고 있는 것 같습니다. @builder를 사용해서 하는 것과 기존 강의에서 나온 방식과 차이가 없는 것일까요??
4. 서비스를 인터페이스로 나뉘어서 작업을 했는데, 추후에 더 다른 서비스를 염두해서 만들어 두신 건가요?? 

5. 서비스 로직의 게시글 전체 조회에서 lv1 요구사항인 "내림차순 정렬" 이 빠져있습니다.
6. 선택한 게시글 조회의 로직(id 찾기 기능)을 수정,삭제에서 사용하고 있는데, 비밀번호 찾기 메서드 처럼 따로 빼는 것은 어떻게 생각하시나요? 게시글 조회 로직을 변경할 때, 수정 삭제도 변경될 가능성이 있어보입니다.
7. 서비스 로직에서 클라이언트로부터 받은 데이터인dto(model)를 return 하는게 아닌 entity 객체 자체를 return하고 있는데, 그 이유가 있을까요?
8. statusres 는 어떤 것을 처리하는지 궁금합니다.
 

* 강의에서 배웠던 기능들과는 다른 새로운 어노테이션과 메서드 등을 활용한 것이 새롭고 좋은 것 같습니다. 주석도 추가해서
설명을 달아주시면 더 쉽고 빠른 이해에 도움이 될 것 같습니다.

* 변수명이 기존 컨벤션들과 달라서 약간의 헷갈림이 있습니다.

**Comment by iksadNorth** [comment]
6번과 7번은 제가 생각하지 못했던 부분이었는데 
다음 과제는 이러한 점에 유의해서 진행해보겠습니다.
